// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNtxa1Va5ki02aHusaXuL0zw5oZ4wSkC8',
    appId: '1:478678510102:web:80602a5b0e782e7e3ce337',
    messagingSenderId: '478678510102',
    projectId: 'mathtarea-c6f74',
    authDomain: 'mathtarea-c6f74.firebaseapp.com',
    storageBucket: 'mathtarea-c6f74.appspot.com',
    measurementId: 'G-YZC8SML65T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7fHASsbdQWL-LwzXd0DfPQHICjZvrJWQ',
    appId: '1:478678510102:android:eceaeea8b3e2d1ac3ce337',
    messagingSenderId: '478678510102',
    projectId: 'mathtarea-c6f74',
    storageBucket: 'mathtarea-c6f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQBEAe1QNv_p0hAbtroPl9E50h0uMa5d8',
    appId: '1:478678510102:ios:60ff8727d114bf393ce337',
    messagingSenderId: '478678510102',
    projectId: 'mathtarea-c6f74',
    storageBucket: 'mathtarea-c6f74.appspot.com',
    iosBundleId: 'com.example.mathtarea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQBEAe1QNv_p0hAbtroPl9E50h0uMa5d8',
    appId: '1:478678510102:ios:bf70ee01043d837f3ce337',
    messagingSenderId: '478678510102',
    projectId: 'mathtarea-c6f74',
    storageBucket: 'mathtarea-c6f74.appspot.com',
    iosBundleId: 'com.example.mathtarea.RunnerTests',
  );
}
